packages:
  - frontend
  - tests
  - email-templates

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  devalue: ^5.3.2
  valibot: ^1.2.0
  validator: ^13.15.22
  cookie: ^0.7.0
  next: ^16.0.10
