package middleware

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

const apiPrefix = "/api"

// NewHostlessAutoPatchNoRouteHandler creates a NoRoute handler that re-routes
// hostless internal GET/PUT requests generated by Huma autopatch from
// /<resource> to /api/<resource> and retries route matching once.
func NewHostlessAutoPatchNoRouteHandler(router *gin.Engine) gin.HandlerFunc {
	return func(c *gin.Context) {
		if shouldRewriteHostlessAutoPatchRequest(c) {
			c.Request.URL.Path = apiPrefix + c.Request.URL.Path
			if c.Request.RequestURI != "" {
				c.Request.RequestURI = c.Request.URL.RequestURI()
			}

			router.HandleContext(c)
			return
		}

		c.String(http.StatusNotFound, "404 page not found")
	}
}

func shouldRewriteHostlessAutoPatchRequest(c *gin.Context) bool {
	if c == nil || c.Request == nil || c.Request.URL == nil {
		return false
	}

	if c.Request.Host != "" {
		return false
	}

	if c.Request.Method != http.MethodGet && c.Request.Method != http.MethodPut {
		return false
	}

	requestPath := c.Request.URL.Path
	if requestPath == "" || !strings.HasPrefix(requestPath, "/") {
		return false
	}

	return !strings.HasPrefix(requestPath, apiPrefix)
}
