FROM alpine:3

ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata curl
RUN mkdir -p /app/data

COPY arcane ./arcane

ENV ENVIRONMENT=production
ENV GIN_MODE=release
ENV PORT=3552

EXPOSE 3552
VOLUME ["/app/data"]

CMD ["./arcane"]