FROM dhi.io/static:20250419-glibc

ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app
RUN apk add --no-cache curl
RUN mkdir -p /app/data

COPY linux/${TARGETARCH}/${TARGETVARIANT}/arcane-agent ./arcane-agent

ENV ENVIRONMENT=production \
    AGENT_MODE=true \
    GIN_MODE=release \
    PORT=3553

EXPOSE 3553
VOLUME ["/app/data"]

CMD ["./arcane-agent"]