FROM dhi.io/static:20250419-glibc

ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app
RUN apk add --no-cache curl
RUN mkdir -p /app/data

COPY linux/${TARGETARCH}/${TARGETVARIANT}/arcane ./arcane

ENV ENVIRONMENT=production
ENV GIN_MODE=release
ENV PORT=3552

EXPOSE 3552
VOLUME ["/app/data"]

CMD ["./arcane"]