FROM gcr.io/distroless/static-debian13

ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app

COPY arcane-agent ./arcane-agent

ENV ENVIRONMENT=production \
    AGENT_MODE=true \
    GIN_MODE=release \
    PORT=3553

EXPOSE 3553
VOLUME ["/app/data"]

CMD ["./arcane-agent"]